const char* vertexSource = "#version 330 core\n"
    "layout (location = 0) in vec3 position;\n"
    "layout (location = 1) in vec3 vertexColors;\n"
    "layout (location = 2) in vec2 aTexCoord;\n"
    "out vec3 v_vertexColors;\n"
    "out vec2 TexCoord;\n"
    "uniform mat4 u_ModelMatrix;\n"
    "uniform mat4 u_PerspMatrix;\n"
    "void main()\n"
    "{\n"
        "v_vertexColors = vertexColors;\n"
        "TexCoord = aTexCoord;\n"
        "vec4 newPosition = u_PerspMatrix * u_ModelMatrix * vec4(position, 1.0f);\n"
        "gl_Position = newPosition;\n"
    "}\0";
